### PR TITLE
Add SpaceRanger processing to pipeline

### LINKED ISSUE #8: Add Docker containers
The workflow currently uses Singularity definition files, which should be converted to Docker and hosted properly on DockerHub. The Singularity images do not list specific versions for the vast majority of packages, which needs to be added. Already existing containers should be used for processes where this is applicable.

### LINKED ISSUE #9: Add pre-processing subworkflow with SpaceRanger
Raw data and pre-processing with SpaceRanger should be included in the workflow. There is already work done on this in a separate repository, whose efforts should be merged in here.

### PR DESCRIPTION
**Pull request by fasterius**
This PR adds a SpaceRanger subworkflow to the pipeline, as well as several other additions, including container directives and labels for most modules as well as separation of single cell parts from the spatial parts. The pipeline can work with either SpaceRanger input (raw FASTQs, images and probesets) or the previous default with SpaceRanger output. More testing is needed to make sure that the SpaceRanger subworkflow works with real data and capture any potential errors.

### CODE REVIEW

**Comment by apeltzer** [comment]
@nf-core-bot fix linting

**Comment by apeltzer** [comment]
How far are we with this @fasterius ?

**Comment by fasterius** [comment]
I'm a bit new to these linting things, so I'm probably missing something, but the errors I'm seeing are either (1) some error in the linters themselves (they doesn't seem to run, but I might be wrong), or (2) `Wrong amount of left-padding spaces(want multiple of 4)` in EditorConfig. I've successfully run the linters locally and added changes accordingly, but this didn't affect anything in terms of checks online. I'm guessing I'm missing something - any ideas, @apeltzer ?

**Comment by apeltzer** [comment]
Likely the pipeline code is out of sync with latest linting / nf-core template 2.6 -- we should merge this one: https://github.com/nf-core/spatialtranscriptomics/pull/21 to spaceranger (changed the base branch now to see where the changes are). I might help on that, but would need to see when I find time for it :-(

**Comment by fasterius** [comment]
Okay, I'll get started on that! (I've been away on parental leave, hence the lack of activity lately)

**Comment by fasterius** [comment]
Linting finally works! Would it be possible to get a review @cavenel so that we might merge it into `dev`?

**Review by cavenel — APPROVED** [review]

**Comment by apeltzer** [comment]
The last missing test is somethign else, will merge this to dev now. You may have to merge in the latest template to get a running lint again on `dev` though.

**Pull request merged**
