### PR TITLE
Embed resources for quarto reports

### PR DESCRIPTION
**Pull request by grst**
## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/spatialtranscriptomics/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/spatialtranscriptomics _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

It might be personal preference, but I suggest to embed resources in quarto HTML reports - that way they can easily be shared via email or downloaded from HPC headnodes without worrying about copying all the resources.

### CODE REVIEW

**Comment by fasterius** [comment]
This exact thing has been tried previously, but does not seem to work on ARM64 (e.g. the newer Macs) for some reason. What system are you on?

**Comment by grst** [comment]
I'm on Scientific linux. This is likely a problem with pandoc then? Let's defer merging this then until it is fixed.

**Comment by fasterius** [comment]
Yes, we figured this wasn't important at the moment and non-embedded resources was fine for now, so let's continue with that.

**Comment by fasterius** [comment]
Okay, I don't know why, but this works now - I was about to do some testing to know what to look for in the future, but it just works. Possibly something had been changed in Pandoc and/or Quarto before I updated the newer multi-platform Docker images, which was picked up by said images and now just works. I tested both with the test dataset as well as a full 10X dataset, and embedded resources work for both.

**Review by fasterius — APPROVED** [review]

**Comment by fasterius** [comment]
Tests are failing since the new test data changes was merged (https://github.com/nf-core/test-datasets/pull/934), so let's merge this as soon as #45 is merged.

**Comment by fasterius** [comment]
This could now be merged if you first merge in the changes on `dev` with the new test data.

**Comment by grst** [comment]
Weird that github didn't show the "update branch" button... anyway, should be good now!

**Pull request merged**
